In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("users_data.csv",dtype={'gender':'category'})

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   category
 6   address            2000 non-null   object
 7   latitude           2000 non-null   float64
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   object
 10  yearly_income      2000 non-null   object
 11  total_debt         2000 non-null   object
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: category(1), float64(2), int64(7), object(4)
memory usage: 205.2+ KB

In [4]:
df.set_index('id',inplace=True)

In [5]:
df['per_capita_income'] = df['per_capita_income'].str.replace('$', '', regex=False).astype(int)

In [6]:
df['yearly_income'] = df['yearly_income'].str.replace('$', '', regex=False).astype(int)

In [7]:
df['total_debt'] = df['total_debt'].str.replace('$', '', regex=False).astype(int)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 825 to 1110
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   current_age        2000 non-null   int64
 1   retirement_age     2000 non-null   int64
 2   birth_year         2000 non-null   int64
 3   birth_month        2000 non-null   int64
 4   gender             2000 non-null   category
 5   address            2000 non-null   object
 6   latitude           2000 non-null   float64
 7   longitude          2000 non-null   float64
 8   per_capita_income  2000 non-null   int64
 9   yearly_income      2000 non-null   int64
 10  total_debt         2000 non-null   int64
 11  credit_score       2000 non-null   int64
 12  num_credit_cards   2000 non-null   int64
dtypes: category(1), float64(2), int64(9), object(1)
memory usage: 205.1+ KB

In [9]:
df.loc[df.isna().any(axis=1)] # NO row has a missing value NaN

Empty DataFrame
Columns: [current_age, retirement_age, birth_year, birth_month, gender, address, latitude, longitude, per_capita_income, yearly_income, total_debt, credit_score, num_credit_cards]
Index: []

In [10]:
df[df['birth_month']> 12] # No wrong entries

Empty DataFrame
Columns: [current_age, retirement_age, birth_year, birth_month, gender, address, latitude, longitude, per_capita_income, yearly_income, total_debt, credit_score, num_credit_cards]
Index: []

In [11]:
df[df['retirement_age']> 80] # No wrong entries

Empty DataFrame
Columns: [current_age, retirement_age, birth_year, birth_month, gender, address, latitude, longitude, per_capita_income, yearly_income, total_debt, credit_score, num_credit_cards]
Index: []

In [12]:
df['gender'].values.categories # only two categories

Index(['Female', 'Male'], dtype='object')

In [13]:
df.loc[(2019 - df['birth_year'] > df['current_age']+1)] # no wrong entry of age and birth year

Empty DataFrame
Columns: [current_age, retirement_age, birth_year, birth_month, gender, address, latitude, longitude, per_capita_income, yearly_income, total_debt, credit_score, num_credit_cards]
Index: []

In [14]:
df.head()

,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
id,,,,,,,,,,,,,
825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,29278,59696,127613,787,5
1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,37891,77254,191349,701,5
1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,22681,33483,196,698,5
708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,163145,249925,202328,722,4
1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,53797,109687,183855,675,1

In [15]:
df.to_csv("users_data_cleaned.csv", index=True)

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [current_age, retirement_age, birth_year, birth_month, gender, address, latitude, longitude, per_capita_income, yearly_income, total_debt, credit_score, num_credit_cards]
Index: []